### ISSUE TITLE
[cem-plugin-custom-jsdoc-tags] Crash when no custom tags provided

### ISSUE THREAD

**Issue by stefanonepanedap** [break-stuff/cem-tools#98]
When analyzing the folder and including in the glob pattern a superClass that doesn't provide any custom tags, the generation crashes.

```bash
.../node_modules/.pnpm/@custom-elements-manifest+analyzer@0.9.3/node_modules/@custom-elements-manifest/analyzer/src/utils/index.js:67
    throw new Error(`\n\n[${name ?? 'unnamed-plugin'}]: ${errorMessage}\n\n ${e.stack}\n`);
          ^

Error: 

[custom-jsdoc-tags-plugin]: Looks like you've hit an error in third party plugin: custom-jsdoc-tags-plugin. Please try to create a minimal reproduction and inform the author of the custom-jsdoc-tags-plugin plugin.

 TypeError: Cannot read properties of undefined (reading 'tags')
    at analyzePhase (.../node_modules/.pnpm/cem-plugin-custom-jsdoc-tags@1.0.1/node_modules/cem-plugin-custom-jsdoc-tags/dist/index.js:406:23)
```

By the way thank you for your great plugins, they help us a lot...

**Comment by pascalvos** [comment]
this is because of the following
https://github.com/break-stuff/cem-tools/blob/main/packages/custom-jsdoc-tags/src/cem-plugin.ts#L63
if i look at the compiled code ` (_c = parsed[0].tags) == null ? void 0 : _c.forEach((tagMeta) => {` it fails on `parsed[0].tags`
`parsed[0]?.tags?.forEach(tagMeta => {` would fix this adding the ? check

the playground with other configuration some how works out of the box making it 
` (_c = parsed[0].tags) === null || _c === void 0 ? void 0 : _c.forEach((tagMeta) => {`

posted in typescript playground
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzmAhlAzgUzgXzgMyghDgCIBjYkTAOxgFpUNMpSBuAKA4Hpu4BeQUOEjBHUJFhwAVHBTo46cgAtMIFASIkKAV3Qxi9TABs1tGOnrqawfJn3su3adI4y4AYQCiAWTgAVAE0ABS8AZTdpbi5MAA9JeGA6FnwUcmwPdHRgojAWGABPODiYWgATBSVVdQA6TPQPPQMQHIg82CKENzhCvIB+AC5EbrgeksHFGCgkgHNOUZxOHBj46ETkqFT0z2JIGnNi2NKaCsUVNRQ6puIvU2o6ABFMcmM0FBhgCBph0fIs1vaH3sE3qAPyBQA2gBdeZwaggABGLHQEwAglAoCgCgAeKoXOqvLI+NRIqAAPlh6B07Re8hRQy6o1GNBQ1Am+mmNDmI2QaQA1igZph2VNZrDRiAIGUdKYRZzuQslisEnAkqVNmkMtcQD4pTLsCVypVzrUAFIoABuKDC5GmYBguulph+cGcriZsn8qjgZWer0xHy+Cgg+DkcL1phqI3do1kADFoD6IOQdPcYO9Pt8wDooJAsOgADRyYzGH1+t6BmgKGDKd5yKDYBtpWsI52EYjRw4JSrKCAyspwJFlpTTJED1QNmpwACSmCL+B0NHIlYUKBOcAgCIAVs8LD1a-B1EUkZ2wLl8sB7BvQ3EEpgB5ud8vCxuoLysve5KuoDNU+ZqxABCLsumboFGHrRKMvq0gGoFohiWLYh4uxfOYFIcMsHC3msqobFsGS+IcxynHitTBPygrYIyrouJ2qLfGgmJFCG+7YJKTpXjWwAKKg5ACkKcCUHQKBJGB0aQeGHHoEM6JMUh2qOvq6HLLwAiiOpQjKjhaopJqnjav4gouhCfKYAUQwcrMUIMjy6hgHkZQAHKssKFmily4qqugslYhMCIQBAphrrCiwYVhqxSDpGrbAA8vaoEuumMz0vp+jEIZ3KYVF+GeL4GUuiybJufKsK9K5LqjKURzFWK3ShVBmCpDKMByrVDUjsA8VfK1HlhRwpjwHoLBxSuQwjQl-CJYK0mIDgBYYZwPC0e43h+PRKDGAUABeLDIMYOgzEkPSAbea4DmVChHZQ4CoXQcKYOmZTvCgkRwAAAkwrIbl1VY7DQ+DAL+sFfN9K6vW9DYwDmVaRNE2FSAuS6VoJ2qmmEDzJhl2T7YdNAABTdG0o1wONQYCBVPTTQyc11fNACULpDVApO-ZNROgYtoyQ9DFOFZgQy6GlID0Fu6BlMm9BJZYYA40kpDzUycgsptO3BLWWB40gFhFjQUpzpJ+oY+QuBDGuBQM9Riu2HAeO676NR8kkA4AISCD0YFhAUwmxAA0k7BJ0k8MEZl8Fs8or3NQDQnkLFwiu-EG8C0lkznUOTduYDUfM1EKMD+CUeN0zHgmJyXN37Hdk3sYbyZ9DU0H+iHVZ1wDJx43jDcVpmQzIeX5gM-wZJlsHlZZy5amTcn6Cp5gRfhyXVZJwZ03kzF267g7ZnoHjTMs2BUtwAAPofs1z-HcADSjQu92mCiTaQbqOPPGc1KLRst9AXjNu3b-JqbNDmwEEPS28df7kDrlLD+UAv4qHbklf+gDB4U3PkJfQlMZgz3JklGoSUZ45wevnI4hdObnyZNbPGKYhZYxqEkF4OhfTb1wS5OmYdSHx0oc0G+-44AAGpJoAAMAA63xZBvQACQICYdQPAEjsHXTTDgfhxdFbLDYTgM+8d1EkMVqg+ATAsADkmvozAeN+ESI4cQLhdB0A4GETIbg-CNGK2MWUCEAAGKEODppQJgcoOBgpiTpgHsA+eCdF7oL3uTXeP197TWdhCJKgTLhJRhKE1UoY8bOySnvVhbC4CR2jmkzCbDdHIFyJgya2SYk1Dsg5TBx90FJK8QqUhpS4jcQ+FyAE5Nrp7HMBCM8bQZ6pJKaXdIIAMo9zykZSaIDz58yGIkh6lw+YTzIPQUgcA+hkE2YsgJyyx7UAVnk30TVjAwD2TMJppyUDNWOWwhhtpOqVkudc+wTyfo1AbDLTUeNuAAD1BEonoNwIspBSB0xwdMEAhciyqQbJKC0V4gplFmD6eQyg0mVQKHkV5ByypbMQGMaqjT8U4uwHgIYi5TlJHvPczR2j47kOdu0-QsxukADIOUROqdxHygC5nsJQhXGAAzykuShOTCE4yMojNIXgEwWB0k235TQ7yCECgUOFf0wZYBhksOQUKvudAxVDIlTUbM6A-EysFE4zRxRjBKvIayzpMxOXcudqqvlGqtXGtFbq-VuTRl+tNXqiVUrem3X9eK6gUIiw2pmHK8+CrHVUSxWXPpJqA3hsnmoDKyjcDzy0TyGmiowpAA

**Comment by break-stuff** [comment]
Yep! That's likely the problem. I should be able to get a quick fix out for this. Thanks!

**Comment by break-stuff** [comment]
This was deployed with v1.0.2. Let me know if you run into any issues.

**Comment by stevenkuster** [comment]
Works like a charm now 🙌

**Comment by stefanonepanedap** [comment]
As @stevenkuster said it works,

Thank you @break-stuff ! 🙇
